### ISSUE TITLE
TOC navigation: nov-visit-relative-file: Couldn’t locate document

### ISSUE THREAD

**Issue by srustamo** [wasamasa/nov.el#13]
Perhaps I'm missing something, but I can't navigate to a location from the TOC with <kbd>Enter</kbd>.

Debugger entered--Lisp error: (error "Couldn’t locate document")
  signal(error ("Couldn’t locate document"))
  error("Couldn't locate document")
  nov-visit-relative-file("Text/cover.html" nil)
  apply(nov-visit-relative-file ("Text/cover.html" nil))
  nov-browse-url(13)
  funcall-interactively(nov-browse-url 13)
  call-interactively(nov-browse-url nil nil)
  command-execute(nov-browse-url)

**Comment by wasamasa** [comment]
Please send me the document via email or IRC, otherwise I cannot debug this.

**Comment by heikkil** [comment]
I am having the same problem. In all epub files I have tried, I can not enter the chapter with enter. The only way I could see something else than the TOC, is to press 'N'.

You can try this book https://www.gutenberg.org/ebooks/1342 . Both epub versions available (with or without images) cause emacs to complain of the same thing. In addition, first press of 'N' shows the toc with header text and next 'N' shows chapter 7. Consecutive presses of 'N' jump to chapters 11, 17, 20, 25, 30, 35, 40, ...

**Comment by wasamasa** [comment]
Please create your own thread instead of hijacking someone else's, otherwise either bug report will be forgotten.  Just because you share the same symptoms doesn't mean it's the same problem.

**Comment by wasamasa** [comment]
@srustamo Please check whether you still get this issue with the latest commit, it should be included in the latest MELPA and MELPA Stable releases, too.

**Comment by srustamo** [comment]
Updated the package. TOC navigation works. But the book is opened in many frames, one per epub constituent file, which is far from ideal. See screencast. 
[novel.mov.zip](https://github.com/wasamasa/nov.el/files/1291674/novel.mov.zip)

GNU Emacs 25.2.1 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21) of 2017-04-26

The book: http://www.gutenberg.org/ebooks/1342#

**Comment by wasamasa** [comment]
Can you reproduce this with the following sequence of commands?

- `emacs -Q`
- `M-x package-initialize`
- `M-: (add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode))`
- `C-x C-f /path/to/pride-and-prejudice.epub`

If not, this is an issue with your Emacs configuration which I cannot help you out with.

**Comment by srustamo** [comment]
Thanks. I've not dealt with packaging for while. Starting with '-Q' switch would mean no package  archives defined. Tried evaluating:

`(require 'package)`
`(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))`

Then:
M-x package-initialize
M-x package-install nov.el

But nov.el is not found. 'package-list-packages' does not show melpa package, what am I doing wrong?

**Comment by wasamasa** [comment]
It isn't necessary to do these at all, provided that you've previously installed this package via package.el, all you need to do is execute `M-x package-initialize` and you'll be able to do things like `M-x find-library RET nov RET`.  Please just stick to the instructions given instead of trying to install it again.

**Comment by srustamo** [comment]
Thanks. Figured out the archive issue. nov.el TOC navigation works as expected with 'emacs -Q'.
