### ISSUE TITLE
Feature request: provide a method to store a link with `org-store-link'

### ISSUE THREAD

**Issue by srustamo** [wasamasa/nov.el#17]
Currently calling `org-store-link` on a rendered EPUB buffer produces `user-error: No method for storing a link from this buffer`.

**Comment by wasamasa** [comment]
This requires implementing Org links for EPUBs first, something that I'd do after implementing a way of remembering the last read position per document/epub.

**Comment by srustamo** [comment]
Feel free to tag this request and stash until good time.

**Comment by jwhitbeck** [comment]
Hi @wasamasa, being able to call `org-store-link` would improve my note-taking workflows. 

I'd be happy to work on a PR, but from your earlier comment, it seems like you have a specific implementation in mind. Could you say more?

**Comment by stardiviner** [comment]
There is an already implemented example:

https://github.com/bddean/emacs-ereader/blob/master/org-ebook.el

I would like this feature too. Because my epub reading need take notes in Org, this is very necessary.

**Comment by inglada** [comment]
Hi,
ereader (which seems unmaintained) has the link support, but nov makes epub reading much, much better. So I would also be very pleased to see this feature available in nov.
Thanks.

**Comment by wasamasa** [comment]
I've done some archeology now and discovered that I've implemented support for restoring last read position on Sep 15, 2017, a whole four days after my last comment. In other words, there's no reason why this couldn't be implemented now, you can restore any position with the following information:

- Identifier / path to file
- Index of the document inside the file
- Position of point in that document

It's not ideal as point can change if the rendering of the EPUB were to change over time, but it's a start.

**Comment by jwhitbeck** [comment]
Thanks for the pointers. I'm hoping to have some time in March to take a stab at this.

**Comment by wasamasa** [comment]
I've pushed a basic implementation of this, it seems to work fine for me. Let me know if there's anything  missing.

**Comment by inglada** [comment]
Hi,
Thanks for the work. The likns work OK, but all the calls to org-store-link try to use nov-org-link-store regardless of the type of buffer org-store-link is called:

```
Debugger entered--Lisp error: (error "Not in a nov.el buffer")
  signal(error ("Not in a nov.el buffer"))
  error("Not in a nov.el buffer")
  nov-org-link-store()
  org-store-link(nil 1)
```

Do you have any idea of what the problem may be? My configuration has this

```
(require 'nov)
(add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode))

```
Thanks.

**Comment by inglada** [comment]
Hi,

I think I found the problem. Here is what works for me:

```
(defun nov-org-link-store ()
  (when (eq major-mode 'nov-mode)   
    (org-store-link-props
     :type "nov"
     :link (format "nov:%s::%d:%d" nov-file-name nov-documents-index (point))
     :description (format "EPUB file at %s" nov-file-name)))
  )

(org-link-set-parameters
 "nov"
 :follow #'nov-org-link-follow
 :store #'nov-org-link-store)
```

It seems that org checks different links types until it finds the one that works, so the candition you were using is too restrictive.

**Comment by wasamasa** [comment]
Funny API, that. Thanks for testing, I've added another commit to address this issue.

**Comment by jwhitbeck** [comment]
I just tested it and it works perfectly. Thanks for adding it!
