### ISSUE TITLE
Enhancement: Being able to extract images and copy them to other files

### ISSUE THREAD

**Issue by hisnawi** [wasamasa/nov.el#20]
I sometimes copy text from EPUBs and keep them in some org files. I was hoping for a feature to be able to also extract images and copy them there as well.

I am not sure if that is even possible to achieve, just throwing it out there in case others are interested in this feature and willing to weigh in.

**Comment by wasamasa** [comment]
Can you please elaborate on a workflow?  What should the user do to extract images and what should happen in what order?

**Comment by hisnawi** [comment]
Just like copying text. Again I am not sure if this is at all possible, but I am expecting some key combination once the image is highlighted to copy it, and when switching to an org document another key combination to paste it there. Would be perfect if same key combination for copying/yanking text is used.

Just like when copying an image in finder then pasting it in a word document.

**Comment by wasamasa** [comment]
Exactly this kind of thing is not supported in Org.  What you could copy-paste is a link, but for that there'd need to be a link to a file, either locally or remote.

**Comment by hisnawi** [comment]
Ok. will then, is it possible to extract the image, copy it to the same directory the org file I am pasting it in then link to it?

**Comment by wasamasa** [comment]
Yeah, that kind of thing would work.  I'd probably just make an interactive function for extracting image at point to an arbitrary location, you could then write your own specific thing for copying it to the org file's location and linking.  I'd prefer to not do too Org-specific things in nov.el as that's a huge rabbit hole.

**Comment by hisnawi** [comment]
Is there a way to extract image at point without the need to change the file into zip....etc?

**Comment by wasamasa** [comment]
Not yet and there won't be if you close this thread prematurely.

**Comment by hisnawi** [comment]
My bad, I hit the wrong key.

**Comment by wasamasa** [comment]
I've looked at this now, extracting an image at point can be generalized beyond nov.el, there isn't really a reason to have it as command in there because you can use it anywhere in Emacs. Here's my first attempt at this, feel free to make it more user-friendly (like detecting permission errors, directories to be created, handling the data case better, ...):

```elisp
(defun my-extract-image-at-point ()
  (interactive)
  (let ((image-spec (plist-get (text-properties-at (point)) 'display)))
    (when (or (not image-spec) (not (eq (car-safe image-spec) 'image)))
      (user-error "No image at point"))
    (cond
     ((memq :file image-spec)
      (let* ((source (plist-get (cdr image-spec) :file))
             (default-file (file-name-nondirectory source))
             (prompt (format "Save %s at " default-file))
             (dest (expand-file-name (read-file-name prompt))))
        (when (file-directory-p dest)
          (setq dest (expand-file-name default-file dest)))
        (copy-file source dest t)
        (message "File saved at %s" dest)))
     ((memq :data image-spec)
      (let* ((data (plist-get (cdr image-spec) :data))
             (dest (expand-file-name (read-file-name "Save at "))))
        (with-temp-file dest
          (insert data))
        (message "File saved at %s" dest)))
     (t (error "Invalid image descriptor")))))
```

**Comment by hisnawi** [comment]
Thank you!
