### ISSUE TITLE
(wrong-type-argument stringp nil) when opening a file

### ISSUE THREAD

**Issue by schvabodka-man** [wasamasa/nov.el#23]
Hello. When opening any epub file i'm getting error with this stacktrace:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-nondirectory(nil)
  file-name-extension(nil)
  (string= (file-name-extension buffer-file-name) "css")
  (if (string= (file-name-extension buffer-file-name) "css") (progn (flycheck-select-checker (quote css-csslint))))
  (lambda nil (if (string= (file-name-extension buffer-file-name) "css") (progn (flycheck-select-checker (quote css-csslint)))))()
  run-hooks(find-file-hook)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer migrating-java-to-the-cloud.epub> "~/Downloads/migrating-java-to-the-cloud.epub" nil nil "~/Downloads/migrating-java-to-the-cloud.epub" (6688817 2050))
  find-file-noselect("/home/ivan/Downloads/migrating-java-to-the-cloud.epub" nil nil nil)
  find-file("/home/ivan/Downloads/migrating-java-to-the-cloud.epub")
  #[257 "\304\305!!r\306\307\310\311\312!\313\"\314$\216\315@\316\"\210	\205
```

The buffer is actually opening but emacs not switching to it(just prints exception), i can only switch to buffer manually. Everything else work as intended

**Comment by wasamasa** [comment]
I'm sorry, but the backtrace clearly shows that the issue isn't related to nov.el, but your hooks.  Something in your `find-file-hook` assumes that `buffer-file-name` is always set which is a faulty assumption (check its docstring, the assumption doesn't hold true for buffers not related to files). Fix that thing (like, by using `css-mode-hook` for Flycheck things).
