### ISSUE TITLE
Can't open some ePub files

### ISSUE THREAD

**Issue by bdillahu** [wasamasa/nov.el#25]
This may very well be an issue with the ePub files, but since Calibre can open them, I thought I would log it...

I try to open the ePub from a dired listing and instead of interpreting the file correctly it just shows the data (all the characters of a binary, compressed file) with the error:

File mode specification error: (error Unique identifier not found by its name: uuid_id)

I'm not sure how to debug further, but if I can get you more data, let me know.

Thanks,
Bruce

**Comment by wasamasa** [comment]
Sounds like an invalid EPUB document which is *not* supported. Please check this by running [epubcheck](https://github.com/IDPF/epubcheck) on it. In case it's actually valid, please send it to me and I'll take a look.

**Comment by bdillahu** [comment]
Thanks, you are correct... seems these are old and don’t include a uuid field.
