### ISSUE TITLE
dired-current-directory: No subdir-alist in <name of epub file>

### ISSUE THREAD

**Issue by analyticd** [wasamasa/nov.el#28]
nov works well for me except for one little glitch. When I have nov set to be the autoloaded mode for epubs, it initially gives the error: dired-current-directory: No subdir-alist in <name of epub file>
when I try to open an epub.

nov does find my unzip and my emacs is GNU Emacs 25.2.1 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21) of 2017-05-22
which I assume has libxml2 compiled in.

Despite the aforementioned error, the file does open in a buffer, but not the current buffer. I can then select the buffer where it is open and use nov fine. Having the error at the time of opening the file makes things like org-noter fail, which is a bummer. Perhaps it has to do with my setup, not sure. Any ideas?

**Comment by wasamasa** [comment]
Please provide proper reproduction steps, ideally as run from a minimal Emacs session (`emacs -Q`). If you fail at reproducing the issue with that kind of setup, it's something in your init file.

**Comment by analyticd** [comment]
It was fine when I ran Emacs without the init file and just installed nov. So nov itself is fine.

**Comment by analyticd** [comment]
I'll just comment here that what causes the problem I was experiencing both in a vanilla install of spacemacs (which I don't use, but tried just for another experiment) and in my custom Emacs config are things in the `find-file-hooks` variable. If I do `(setq find-file-hooks nil)` and then open the file, `nov` opens the epub file and it appears in the current buffer as desired. Hopefully this will help someone else. One just needs to bisect the various `find-file-hooks` to find which one (or ones) is to blame. In my config's case it turned out to be `cvs-insert-visited-file`. The following fixes things up less indiscriminately than setting to nil: `(setq find-file-hooks (delq 'csv-insert-visited-file find-file-hooks))`. In the case of spacemacs, this does the trick: `(setq find-file-hooks (delq 'find-file-hook--open-junk-file find-file-hooks))`. I found these by successively executing (setq find-file-hooks (delq (first find-file-hooks) find-file-hooks)) then retrying opening an epub with `(setq debug-on-error t)` first set. Again, just leaving here for some other poor soul who runs into this.
