### ISSUE TITLE
Inhibition of autosave and save questions deletes buffer-file-name

### ISSUE THREAD

**Issue by weirdNox** [wasamasa/nov.el#34]
Hello! A while back I added support of nov.el to org-noter and I think it has been working well.

Org-noter has a feature to create the annotation session from the document itself, by finding a notes file in a parent directory. In order to do that, it needs to know the full name of the file, and up until now it was using `buffer-file-name` for that.

However, the line `(set-visited-file-name nil t) ; disable autosaves and save questions` explicitly deletes it in order to avoid saving the file incorrectly, I think. Is there a way to do that that doesn't involve deleting that variable?

Another thing you could do is save value of the variable before deleting it and then assigning it to another variable, I think that would work :)

We are tracking this issue on weirdNox/org-noter#26.

**Comment by weirdNox** [comment]
I just found `write-contents-functions` which I think can help in this situation!

> If any of the functions in this hook returns non-nil, the file is considered already written and the rest are not called and neither are the functions in write-file-functions. 

Edit: Just checked that `(add-hook 'write-contents-functions (lambda () (set-buffer-modified-p nil) t) nil t)` prevents saving the file and removes the modification flag.

This, together with setting `buffer-auto-save-file-name` to nil and setting the modified flag to false when changing the buffer, may do what you want and keep the file information.

**Comment by wasamasa** [comment]
Sorry, but I don't think `write-contents-functions` is the way to go. From the Emacs 26.1 `NEWS`:

> ** Functions in 'write-contents-functions' can fully short-circuit the
> 'save-buffer' process.  Previously, saving a buffer that was not
> visiting a file would always prompt for a file name.  Now it only does
> so if 'write-contents-functions' is nil (or all its functions return
> nil).

I'd therefore go for the stupidly simple solution, using a new variable to store the original path. Any special name wishes?

**Comment by weirdNox** [comment]
Ok, while I don't see why the passage you cited is bad (the hook would be local, so it would only prevent your buffer from saving), using that would probably imply having some refactoring and not so trivial code in you package.

You can name it what you want, I only ask for it to be nil when not set :)

In the meantime I think I solved the issue submitted to my package by having it use `buffer-file-truename` when `buffer-file-name` is not set, and by using `default-directory` to try to infer the path with symlinks (and fall backing to `buffer-file-truename` when `default-directory` is not set to the directory of the file). It seems that `buffer-file-truename` is still set even after telling Emacs to stop visiting a file!

Anyway, thanks for the quick response!

**Comment by wasamasa** [comment]
You can now check `nov-file-name`.
