### ISSUE TITLE
Add Emacspeak support

### ISSUE THREAD

**Issue by devinprater** [wasamasa/nov.el#35]
Emacspeak, found at
http://www.github.com/tvraman/emacspeak/
is an auditory interface to Emacs. As a blind user of Emacs, I use it as a sort of operating system for all my textual needs, including reading books. Nov-mode works well now, but there could be some improvements.
Usually, in modes like Info, pressing space not only scrolls, but speaks the scrolled text. In nov-mode, C-v speaks and scrolls, but space only seems to scroll a few lines down.
In info-mode, pressing N or P speaks the whole entry. Perhaps this would not be desirable in nov-mode, but at least speaking the chapter name would be fine.
Whenever an image is encountered, pressing C-n does not go passed the image, but I can get around that by pressing C-f a few times, then C-n to continue down through lines.
Everything else works fine, and I love using Nov-mode, as it's the only accessible Epub reader I have on the Mac.

**Comment by wasamasa** [comment]
I'm sorry, but I don't see how I can help. From my cursory understanding, emacspeak achieves its enhancements by using advice on Emacs and Emacs packages. It's emacspeak that contains special integration for info to speak the relevant text, not info. Similarly, emacspeak would need to add special integration for nov.el, not nov.el itself. Please contact the emacspeak author on how one can integrate a new package.
