### ISSUE TITLE
Jump back to the previous location?

### ISSUE THREAD

**Issue by phlo46** [wasamasa/nov.el#36]
Sometimes I jump to:
  - notes in `Bibliography`
  - a new Chapter

![Demo](https://media.giphy.com/media/82SkH4TF8oTC3HTnRB/giphy.gif)

but have no idea how to go back. 

My current solution is pressing `t` and finding the previous chapter, location manually. But it's a very bad experience.

**Comment by wasamasa** [comment]
There is no such feature yet. Your ebook seems to have backlinks though that would allow to jump back to the place the footnote was referenced, so try visiting these.

**Comment by mykhas** [comment]
@wasamasa I don't have backlinks in a lot of my books and will be happy to have this feature. If you have any thoughts on its correct implementation, please share it, and probably I would be able to contribute into it.

**Comment by wasamasa** [comment]
Thanks to @jakub-w this feature is implemented now.
