### ISSUE TITLE
Can't read some pages due to url encoded references

### ISSUE THREAD

**Issue by licebmi** [wasamasa/nov.el#39]
I have this epub that throws an error about not finding the xhtml file when reading some pages.
The xhtml file does exist, but it contains spaces, so it's url encoded on the content.opf

Here is the traceback.
```
Debugger entered--Lisp error: (file-missing "Opening input file" "No such file or directory" "/tmp/nov-exk8tU.epub/OEBPS/2.%20The%20Political%20Arithmetic%20of%20Piracy.xhtml")
  insert-file-contents("/tmp/nov-exk8tU.epub/OEBPS/2.%20The%20Political%20Arithmetic%20of%20Piracy.xhtml")
  nov-slurp("/tmp/nov-exk8tU.epub/OEBPS/2.%20The%20Political%20Arithmetic%20of%20Piracy.xhtml")
  nov-render-document()
  nov-next-document()
  funcall-interactively(nov-next-document)
  call-interactively(nov-next-document nil nil)
  command-execute(nov-next-document)
```

While epubcheck does throw a few warnings, and recommends avoiding spaces as they need to be url encoded, as far as I have researched, it doesn't seem to be against the standard.

It doesn't seem to be a bad idea to url decode this references.

**Comment by wasamasa** [comment]
Fun, my last fix was about urldecoding link targets. I didn't think that there would be more.

Judging from the backtrace this happens while figuring out the content files. Could you please send me the problematic file for further analysis?

**Comment by licebmi** [comment]
Actually, I thought I had the latest version, and didn't even noticed the last commit.
Either way, the book still doesn't work although it seems like the reference is being url decoded.

new trace in here:
Debugger entered--Lisp error: (error "Couldn’t locate document")
  signal(error ("Couldn’t locate document"))
  error("Couldn't locate document")
  nov-visit-relative-file("2. The Political Arithmetic of Piracy.xhtml" "")
  apply(nov-visit-relative-file ("2. The Political Arithmetic of Piracy.xhtml" ""))
  nov-browse-url(13)
  funcall-interactively(nov-browse-url 13)
  call-interactively(nov-browse-url nil nil)
  command-execute(nov-browse-url)

Also, in the new version, even when the page is displayed, there's still an error on the same function, this happens on different books.
Trace:
Debugger entered--Lisp error: (error "Couldn’t locate target")
  signal(error ("Couldn’t locate target"))
  error("Couldn't locate target")
  nov-visit-relative-file("Index.xhtml" "")
  apply(nov-visit-relative-file ("Index.xhtml" ""))
  nov-browse-url(13)
  funcall-interactively(nov-browse-url 13)
  call-interactively(nov-browse-url nil nil)
  command-execute(nov-browse-url)

Will sent you the problematic file.

**Comment by licebmi** [comment]
After a reviewing, it seems like we can't find an index because nov-find-document tries to compare the a url-decoded path with the url-encoded path on nov-documents, so it won't find anything.

**Comment by wasamasa** [comment]
That's right. I've used this chance to urldecode all things looking like an URL and with that I've managed to open "2. The Political Arithmetic of Piracy". However opening the next document fails because the file names on disk are encoded differently from the file names in the EPUB file. `epubcheck` throws lots of errors for these, so I won't look any further into that specific issue.
