### ISSUE TITLE
Bookmarking last position

### ISSUE THREAD

**Issue by dov** [wasamasa/nov.el#46]
If reopening an epub, I'd like to automatically jump to the position where I left off.

**Comment by wasamasa** [comment]
This feature is a thing, see `nov-saved-place` and its use in `nov-mode`. If it doesn't work for you, you're most likely using an erroneous EPUB without a valid identifier or a proper identifier declaration. Check the `*Warnings*` buffer for a "Couldn't restore last position" and if present, check the EPUB with `epubcheck`. In case it's valid, please send me a copy for further debugging.
