### ISSUE TITLE
Feature Request: Configure Progress File Location

### ISSUE THREAD

**Issue by jeffjewiss** [wasamasa/nov.el#48]
Hi, thanks for this library, I'm enjoying using it so far.

Is it possible to configure where the `nov-places` file is created and accessed? It seems like by default it's created in my `.emacs.d` directory and I'm not sure if this is intended or due to configuration I have elsewhere. I have this directory under version control, so I was hoping to save `nov-places` elsewhere if possible.

Thanks!

**Comment by wasamasa** [comment]
This is a matter of customizing `nov-save-place-file`.

**Comment by jeffjewiss** [comment]
Thanks! That worked great, I appreciate the fast response.
