### ISSUE TITLE
should support .dir-locals.el

### ISSUE THREAD

**Issue by GregorZattler** [wasamasa/nov.el#53]
It would be helpful if nov.el would evaluate a .dir-locals.el file.  I use this e.g. to set up dictionary lookup for my ebooks.

Thanks for nov.el it's really useful.

**Comment by wasamasa** [comment]
Interesting usecase. The fix is as easy as adding `hack-dir-local-variables-non-file-buffer` (I'm not making this up) to `nov-mode-hook`. Several other modes in Emacs do this, so I've added it to nov.el as well.

**Comment by GregorZattler** [comment]
Hi Vasilij,
* Vasilij Schneidermann <notifications@github.com> [2019-06-11; 02:23]:
> Interesting usecase. The fix is as easy as adding
> `hack-dir-local-variables-non-file-buffer` (I'm not making this
> up) to `nov-mode-hook`. Several other modes in Emacs do this,
> so I've added it to nov.el as well.

works like a charm.  Thank you very much!

Ciao; Gregor
--
 -... --- .-. . -.. ..--.. ...-.-
