### ISSUE TITLE
Font Size and Text Width

### ISSUE THREAD

**Issue by guilherme-salome** [wasamasa/nov.el#54]
I have been playing with `nov-text-width` and the command `text-scale-adjust` to get the text at a size suitable to my small screen.
However, I found an issue I have no idea how to fix, but I know how to replicate.

**Issue:**
If I set `(setq nov-text-width 45)` and open a book, then I see the following:
<img width="1280" alt="Screen Shot 2019-07-18 at 2 55 26 PM" src="https://user-images.githubusercontent.com/7663115/61487654-16777380-a96c-11e9-9b39-c5078dc60b66.png">

If I scroll to the next page with `SPC`, I get the following view:
<img width="1280" alt="Screen Shot 2019-07-18 at 2 57 13 PM" src="https://user-images.githubusercontent.com/7663115/61487784-550d2e00-a96c-11e9-91c5-1cfb5c6ee0a0.png">

If I scroll back to the previous page with `S-SPC`, then I get the following view:
<img width="1280" alt="Screen Shot 2019-07-18 at 2 58 00 PM" src="https://user-images.githubusercontent.com/7663115/61487836-7110cf80-a96c-11e9-9609-6a4999cfce86.png">

It seems that when I first open the book, the column width is not being completely respected.
After moving to the next page, the text gets rearranged to fit a smaller width.
Now, when I move back to the original page, the text that was previously displayed over a larger width, is now rearranged to occupy a smaller width.

**Comment by wasamasa** [comment]
Don't use `text-scale-adjust` for anything other than interactive changes to text display. The README explains in "Default font" how to customize the default font.
