### ISSUE TITLE
Invalid image type

### ISSUE THREAD

**Issue by ghost** [wasamasa/nov.el#55]
I built Emacs 26.2 on Gentoo with the following configure settings: `--without-x --without-imagemagick --without-jpeg --without-png --without-gif --without-tiff`.

But I get the following error messages when opening an EPUB book with images with nov.el:

> Invalid image type ‘jpeg’

Or:

> Invalid image type ‘gif’

Or:

> Invalid image type ‘png’

I can reproduce this problem with multiple, different e-books.

I'm using nov.el 20190611.922 from MELPA.

**Comment by wasamasa** [comment]
This is not a complete reproducer as it's missing an actual ebook to reproduce the issue.

**Comment by ghost** [comment]
I cannot attach the e-book here due to copyright issues. But I can send you the e-book privately via e-mail if you want...

**Comment by ghost** [comment]
Sent.

**Comment by wasamasa** [comment]
Thanks, I've figured out how `eww` avoids that error and implemented something equivalent.
