### ISSUE TITLE
Unable to run nov-mode on Windows

### ISSUE THREAD

**Issue by lvictorino** [wasamasa/nov.el#58]
Hey, disclaimer: I'm still relatively new to Emacs.

When I open an Epub on Windows, Emacs opens it using Zip-Archive mode and displays its content (which is normal afaik).

![image](https://user-images.githubusercontent.com/18822/63836129-45283700-c979-11e9-947d-0cb4f83e6b0d.png)

 However, when I start nov-mode, encoded characters are displayed and I got an error of "Wrong type argument: stringp, nil" in the mini-buffer.

![image](https://user-images.githubusercontent.com/18822/63836267-84ef1e80-c979-11e9-979b-619656a070c0.png)

What should I do? Where should I look?
Thanks for the help.

**Comment by wasamasa** [comment]
You seem to be the same person as on https://emacs.stackexchange.com/questions/52426/unable-to-run-nov-mode-on-windows so I'm closing this one.
