### ISSUE TITLE
EPUB buffer is not associated its original file or at least it does not show its file path in *Buffer list*

### ISSUE THREAD

**Issue by soulawaker** [wasamasa/nov.el#60]
I'm using `pesrp-mode` in spacemacs to save and restore the last buffers and the layout of workspaces. When persp has tried to restore EPUB buffer, it has spitted the message "EPUB must be associated with file" . I'm not sure that persp-mode really requires buffer-associated file path. But in case of PDFView buffer it is associated with its file path and show it in `*Buffer List*`. So I guess that if `nov` make EPUB buffer associated with its file path then persp-mode can restore it. Could I expect some improvement?

**Comment by soulawaker** [comment]
I've tried to insert a epub file path to persp-auto-save file. But failed to restore. Even stored nov-mode buffer prevents persp-mode from restoring rest things.

**Comment by scottdw** [comment]
I assume it is due to https://github.com/wasamasa/nov.el/blob/master/nov.el#L720 but not sure how to go about fixing it.

**Comment by soulawaker** [comment]
@scottdw Thanks for refering that point.
Its main problem is the deletion of `buffer-file-name`. The persp-mode use it to save a buffer. But only restoring its value did not solve the problem. I've made workaround using persp-mode's [custom-saveload-buffer-function](https://github.com/Bad-ptr/persp-mode.el#custom-saveload-buffer-function-example). I leave [my gist link of the solution](https://gist.github.com/Bad-ptr/1aca1ec54c3bdb2ee80996eb2b68ad2d#file-persp-ivy-el) for anyone to find this
