### ISSUE TITLE
Goto chapter completion menu

### ISSUE THREAD

**Issue by clemera** [wasamasa/nov.el#69]
It would be great to be able to jump to any section in the ebook similar to `counsel-outline` or `helm-org-goto-heading`. `Imenu` support would also be possible as `imenu--index-alist` allows defining special elements with custom goto functions but this would be a bit unusual because normally `imenu` is only used for "in buffer" navigation.

**Comment by wasamasa** [comment]
Why not jump to the TOC instead? From there on you can go to any section defined there.

**Comment by clemera** [comment]
Yes, there are multiple ways. I thought it would be a nice feature (and the data should be available in the metadata of the ebook AFAIK) but if you disagree feel free to close this.

**Comment by wasamasa** [comment]
The thing is that the data for that feature is inside the TOC document.  For EPUB2 it's a NCX file which happens to be standardized XML, for EPUB3 it's a HTML file like any other document inside the EPUB.  This means that parsing is required to extract the links from either to make an imenu alist and for the EPUB3 case there might be discrepancies compared to what you see in the TOC, depending on the level of HTML craziness.

Anyway, I don't think this will be too hard, but it's not as straightforward as you've described either.  I'm just pointing out that this is basically a glorified "Go to TOC item".  Do you still want me to work on this feature?

**Comment by clemera** [comment]
This sounds not as straightforward as I thought.

> Do you still want me to work on this feature?

No, I'm a nice person ;). If I get around to it I may give it a try myself in case you would potentially accept a PR for this.

**Comment by wasamasa** [comment]
Would you mind testing this now? I find it bizarre that Imenu replaces spaces with periods, but other than that it seems to work fine.

**Comment by clemera** [comment]
Great, thank you very much for working on this! 

> I find it bizarre that Imenu replaces spaces with periods

You can avoid this using:

    (setq imenu-space-replacement nil)    

 It worked one time but then I got:

    Debugger entered--Lisp error: (wrong-type-argument stringp (span ((class . "toc-secnum")) " "))
      string-match("\\`Chapter\\'" (span ((class . "toc-secnum")) " "))
      imenu-find-default(#("Chapter" 0 7 (face variable-pitch)) (("*Rescan*" . -99) ((span ((class . "toc-secnum")) " ") "f_0003.xhtml" nov-imenu-goto-function "chp.changes") ("B2.0: February 14, 2020" "f_0004.xhtml" nov-imenu-goto-function "d24e38") ("B1.0: October 22, 2019" "f_0005.xhtml" nov-imenu-goto-function "d24e50") ((span ((class . "toc-secnum")) " ") "f_0006.xhtml" nov-imenu-goto-function "chp.preface") ("What’s in This Book" "f_0007.xhtml" nov-imenu-goto-function "d24e70") ("How to Use This Book" "f_0008.xhtml" nov-imenu-goto-function "d24e224") ("About Example Code" "f_0009.xhtml" nov-imenu-goto-function "sec.PrefaceBookCode") ("Go Modules" "f_0010.xhtml" nov-imenu-goto-function "sec.PrefaceGoModules") ("Online Resources" "f_0011.xhtml" nov-imenu-goto-function "d24e603") ((span ((class . "toc-secnum")) "1. ") "f_0012.xhtml" nov-imenu-goto-function "chp.YourFirstCLI") ("Building the Basic Word Counter" "f_0013.xhtml" nov-imenu-goto-function "sec.GoFirstTool") ("Testing the Basic Word Counter" "f_0014.xhtml" nov-imenu-goto-function "sec.GoFirstToolTesting") ("Adding Command Line Flags" "f_0015.xhtml" nov-imenu-goto-function "sec.GoFirstToolLineCount") ("Compiling your Tool for Different Platforms" "f_0016.xhtml" nov-imenu-goto-function "sec.GoFirstToolCrossCompile") ("Exercises" "f_0017.xhtml" nov-imenu-goto-function "sec.IntroductionExercises") ("Wrapping Up" "f_0018.xhtml" nov-imenu-goto-function "sec.IntroductionWrappingUp") ((span ((class . "toc-secnum")) "2. ") "f_0019.xhtml" nov-imenu-goto-function "chp.BasicIO") ("Organizing your Code" "f_0020.xhtml" nov-imenu-goto-function "sec.todoOrganizingCode") ("Defining the To-Do API" "f_0021.xhtml" nov-imenu-goto-function "sec.todoAPI") ("Creating the Initial " "f_0022.xhtml" nov-imenu-goto-function "sec.InitialToDoCLI") ("Testing the Initial CLI Implementation" "f_0023.xhtml" nov-imenu-goto-function "sec.todoBasicTests") ("Handling Multiple Command Line Options" "f_0024.xhtml" nov-imenu-goto-function "sec.todoFlags") ("Display Command Line Tool Usage" "f_0025.xhtml" nov-imenu-goto-function "sec.todoUsage") ("Improving the List Output Format" "f_0026.xhtml" nov-imenu-goto-function "sec.todoImprovingOutput") ("Increasing Flexibility with Environment Variables" "f_0027.xhtml" nov-imenu-goto-function "sec.todoEnvVars") ("Capturing Input from STDIN" "f_0028.xhtml" nov-imenu-goto-function "sec.todoSTDIN") ("Exercises" "f_0029.xhtml" nov-imenu-goto-function "sec.BasicIOExercises") ("Wrapping Up" "f_0030.xhtml" nov-imenu-goto-function "sec.BasicIOWrapUp") ((span ((class . "toc-secnum")) "3. ") "f_0031.xhtml" nov-imenu-goto-function "chp.Files") ("Creating a Basic Markdown Preview Tool" "f_0032.xhtml" nov-imenu-goto-function "sec.BasicMarkdownPreview") ("Writing Tests for the Markdown Preview Tool" "f_0033.xhtml" nov-imenu-goto-function "sec.TestingMarkdownPreview") ("Adding Temporary Files to the Markdown Preview Tool" "f_0034.xhtml" nov-imenu-goto-function "sec.MarkdownPreviewTempFiles") ("Using Interfaces to Automate Tests" "f_0035.xhtml" nov-imenu-goto-function "sec.TestingMarkdownPreviewInterfaces") ("Adding an Auto-Preview Feature" "f_0036.xhtml" nov-imenu-goto-function "sec.MarkdownPreviewAutoPreview") ("Cleaning Up Temporary Files" "f_0037.xhtml" nov-imenu-goto-function "sec.MarkdownPreviewCleanUp") ("Improving the Markdown Preview Tool with Templates" "f_0038.xhtml" nov-imenu-goto-function "sec.MarkdownPreviewTemplates") ("Exercises" "f_0039.xhtml" nov-imenu-goto-function "sec.fileExercises") ("Wrapping Up" "f_0040.xhtml" nov-imenu-goto-function "sec.fileWrapUp") ((span ((class . "toc-secnum")) "4. ") "f_0041.xhtml" nov-imenu-goto-function "chp.Directories") ("Developing a File System Crawler" "f_0042.xhtml" nov-imenu-goto-function "sec.fileIntroCrawler") ("Testing with Table Driven Testing" "f_0043.xhtml" nov-imenu-goto-function "sec.fileIntroCrawlerTesting") ("Deleting Matched Files" "f_0044.xhtml" nov-imenu-goto-function "sec.fileCrawlerDelete") ("Testing with the Help of Test Helpers" "f_0045.xhtml" nov-imenu-goto-function "sec.fileCrawlerDeleteTesting") ("Logging Deleted Files" "f_0046.xhtml" nov-imenu-goto-function "sec.fileCrawlerLogging") ("Archiving Files" "f_0047.xhtml" nov-imenu-goto-function "sec.fileCrawlerArchive") ("Exercises" "f_0048.xhtml" nov-imenu-goto-function "sec.DirectoriesExercises") ("Wrapping Up" "f_0049.xhtml" nov-imenu-goto-function "sec.DirectoriesWrapUp") ((span ((class . "toc-secnum")) "5. ") "f_0050.xhtml" nov-imenu-goto-function "chp.ImprovePerformance") ("Developing the Initial Version of " "f_0051.xhtml" nov-imenu-goto-function "sec.ColStats") ...))
      imenu--completion-buffer((("*Rescan*" . -99) ((span ((class . "toc-secnum")) " ") "f_0003.xhtml" nov-imenu-goto-function "chp.changes") ("B2.0: February 14, 2020" "f_0004.xhtml" nov-imenu-goto-function "d24e38") ("B1.0: October 22, 2019" "f_0005.xhtml" nov-imenu-goto-function "d24e50") ((span ((class . "toc-secnum")) " ") "f_0006.xhtml" nov-imenu-goto-function "chp.preface") ("What’s in This Book" "f_0007.xhtml" nov-imenu-goto-function "d24e70") ("How to Use This Book" "f_0008.xhtml" nov-imenu-goto-function "d24e224") ("About Example Code" "f_0009.xhtml" nov-imenu-goto-function "sec.PrefaceBookCode") ("Go Modules" "f_0010.xhtml" nov-imenu-goto-function "sec.PrefaceGoModules") ("Online Resources" "f_0011.xhtml" nov-imenu-goto-function "d24e603") ((span ((class . "toc-secnum")) "1. ") "f_0012.xhtml" nov-imenu-goto-function "chp.YourFirstCLI") ("Building the Basic Word Counter" "f_0013.xhtml" nov-imenu-goto-function "sec.GoFirstTool") ("Testing the Basic Word Counter" "f_0014.xhtml" nov-imenu-goto-function "sec.GoFirstToolTesting") ("Adding Command Line Flags" "f_0015.xhtml" nov-imenu-goto-function "sec.GoFirstToolLineCount") ("Compiling your Tool for Different Platforms" "f_0016.xhtml" nov-imenu-goto-function "sec.GoFirstToolCrossCompile") ("Exercises" "f_0017.xhtml" nov-imenu-goto-function "sec.IntroductionExercises") ("Wrapping Up" "f_0018.xhtml" nov-imenu-goto-function "sec.IntroductionWrappingUp") ((span ((class . "toc-secnum")) "2. ") "f_0019.xhtml" nov-imenu-goto-function "chp.BasicIO") ("Organizing your Code" "f_0020.xhtml" nov-imenu-goto-function "sec.todoOrganizingCode") ("Defining the To-Do API" "f_0021.xhtml" nov-imenu-goto-function "sec.todoAPI") ("Creating the Initial " "f_0022.xhtml" nov-imenu-goto-function "sec.InitialToDoCLI") ("Testing the Initial CLI Implementation" "f_0023.xhtml" nov-imenu-goto-function "sec.todoBasicTests") ("Handling Multiple Command Line Options" "f_0024.xhtml" nov-imenu-goto-function "sec.todoFlags") ("Display Command Line Tool Usage" "f_0025.xhtml" nov-imenu-goto-function "sec.todoUsage") ("Improving the List Output Format" "f_0026.xhtml" nov-imenu-goto-function "sec.todoImprovingOutput") ("Increasing Flexibility with Environment Variables" "f_0027.xhtml" nov-imenu-goto-function "sec.todoEnvVars") ("Capturing Input from STDIN" "f_0028.xhtml" nov-imenu-goto-function "sec.todoSTDIN") ("Exercises" "f_0029.xhtml" nov-imenu-goto-function "sec.BasicIOExercises") ("Wrapping Up" "f_0030.xhtml" nov-imenu-goto-function "sec.BasicIOWrapUp") ((span ((class . "toc-secnum")) "3. ") "f_0031.xhtml" nov-imenu-goto-function "chp.Files") ("Creating a Basic Markdown Preview Tool" "f_0032.xhtml" nov-imenu-goto-function "sec.BasicMarkdownPreview") ("Writing Tests for the Markdown Preview Tool" "f_0033.xhtml" nov-imenu-goto-function "sec.TestingMarkdownPreview") ("Adding Temporary Files to the Markdown Preview Tool" "f_0034.xhtml" nov-imenu-goto-function "sec.MarkdownPreviewTempFiles") ("Using Interfaces to Automate Tests" "f_0035.xhtml" nov-imenu-goto-function "sec.TestingMarkdownPreviewInterfaces") ("Adding an Auto-Preview Feature" "f_0036.xhtml" nov-imenu-goto-function "sec.MarkdownPreviewAutoPreview") ("Cleaning Up Temporary Files" "f_0037.xhtml" nov-imenu-goto-function "sec.MarkdownPreviewCleanUp") ("Improving the Markdown Preview Tool with Templates" "f_0038.xhtml" nov-imenu-goto-function "sec.MarkdownPreviewTemplates") ("Exercises" "f_0039.xhtml" nov-imenu-goto-function "sec.fileExercises") ("Wrapping Up" "f_0040.xhtml" nov-imenu-goto-function "sec.fileWrapUp") ((span ((class . "toc-secnum")) "4. ") "f_0041.xhtml" nov-imenu-goto-function "chp.Directories") ("Developing a File System Crawler" "f_0042.xhtml" nov-imenu-goto-function "sec.fileIntroCrawler") ("Testing with Table Driven Testing" "f_0043.xhtml" nov-imenu-goto-function "sec.fileIntroCrawlerTesting") ("Deleting Matched Files" "f_0044.xhtml" nov-imenu-goto-function "sec.fileCrawlerDelete") ("Testing with the Help of Test Helpers" "f_0045.xhtml" nov-imenu-goto-function "sec.fileCrawlerDeleteTesting") ("Logging Deleted Files" "f_0046.xhtml" nov-imenu-goto-function "sec.fileCrawlerLogging") ("Archiving Files" "f_0047.xhtml" nov-imenu-goto-function "sec.fileCrawlerArchive") ("Exercises" "f_0048.xhtml" nov-imenu-goto-function "sec.DirectoriesExercises") ("Wrapping Up" "f_0049.xhtml" nov-imenu-goto-function "sec.DirectoriesWrapUp") ((span ((class . "toc-secnum")) "5. ") "f_0050.xhtml" nov-imenu-goto-function "chp.ImprovePerformance") ("Developing the Initial Version of " "f_0051.xhtml" nov-imenu-goto-function "sec.ColStats") ...) nil)
      imenu-choose-buffer-index()
      byte-code("\300 C\207" [imenu-choose-buffer-index] 1)
      call-interactively(imenu nil nil)
      command-execute(imenu)

It seems to happen because `imenu--index-alist` contains some wrong formatted elements like:

    ((span
       ((class . "toc-secnum"))
       " ")
      "f_0003.xhtml" nov-imenu-goto-function "chp.changes")

**Comment by clemera** [comment]
See PR #71
