### ISSUE TITLE
Zooming in

### ISSUE THREAD

**Issue by kaygdotorg** [wasamasa/nov.el#70]
When zooming in, that is, increasing the font size: only the Emacs UI elements seem to get enlarged while the text on the ePUB stays the same. This is rather inconvenient as scaling of text is an important feature to have while reading a book or a document.

**Comment by wasamasa** [comment]
Are you speaking of `C-x C-+`? That's a side effect of how it's implemented, it will only change the size of the default face. There's two ways of working around that:

- Adjust nov.el rendering to use the default face (customize `nov-variable-pitch` or mess around with shr.el)
- Use a better zooming command than that. I wrote my own that instead changes the frame font, this has the benefit of working everywhere.
